[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "lidar_hd_tools"
version = "0.1.6"
authors = [
  { name="Thibault Chardon", email="pypi.flaxseed411@passinbox.com" },
]
description = "Python library for quick use of IGN's LiDAR-HD data."
readme = "ReadMe.md"
requires-python = ">=3.10"
dependencies = [
    "cartopy",
	"cmcrameri",
	"geopandas",
	"laspy",
	"matplotlib",
	"numpy",
	"owslib",
	"pandas",
	"rasterio",
	"requests",
	"rioxarray",
	"rvt-py",
	"scipy",
	"shapely",
	"tqdm",
	"xarray",
]

classifiers = [
    "Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
license = "CC0-1.0"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/Thibalt-C/lidar_hd_tools"